listen_port = 9999

[auth]
api_secret = "Rst$qSCiyv7bJTttZ7ht8reyTsB8jv@Q"
token_expire = 86400

[log]
level = "info"

[db]
# sqlite
url = "sqlite://test.db"

# postgres
# url = "postgres://postgres:postgres@192.168.16.110:5432/postgres"

# mysql
# url = "root:root@tcp(192.168.16.110:3306)/test"
