// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: rpc/hello.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	HelloWrold_SayHello_FullMethodName = "/rpc.HelloWrold/SayHello"
)

// HelloWroldClient is the client API for HelloWrold service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloWroldClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloWroldClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloWroldClient(cc grpc.ClientConnInterface) HelloWroldClient {
	return &helloWroldClient{cc}
}

func (c *helloWroldClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, HelloWrold_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWroldServer is the server API for HelloWrold service.
// All implementations should embed UnimplementedHelloWroldServer
// for forward compatibility
type HelloWroldServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedHelloWroldServer should be embedded to have forward compatible implementations.
type UnimplementedHelloWroldServer struct {
}

func (UnimplementedHelloWroldServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// UnsafeHelloWroldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloWroldServer will
// result in compilation errors.
type UnsafeHelloWroldServer interface {
	mustEmbedUnimplementedHelloWroldServer()
}

func RegisterHelloWroldServer(s grpc.ServiceRegistrar, srv HelloWroldServer) {
	s.RegisterService(&HelloWrold_ServiceDesc, srv)
}

func _HelloWrold_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWroldServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloWrold_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWroldServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloWrold_ServiceDesc is the grpc.ServiceDesc for HelloWrold service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloWrold_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.HelloWrold",
	HandlerType: (*HelloWroldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloWrold_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/hello.proto",
}
