definitions:
  schema.ReqLogin:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  schema.ReqRegister:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  schema.ResLogin:
    properties:
      access_token:
        type: string
    type: object
  schema.ResLogout:
    properties:
      message:
        type: string
    type: object
  schema.ResRegister:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      description: User Login
      parameters:
      - description: User Login
        in: body
        name: schema.ReqLogin
        required: true
        schema:
          $ref: '#/definitions/schema.ReqLogin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.ResLogin'
      summary: Login
      tags:
      - Auth
  /auth/logout:
    post:
      description: User Logout
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.ResLogout'
      summary: Logout
      tags:
      - Auth
  /auth/register:
    post:
      description: User Register
      parameters:
      - description: User Register
        in: body
        name: schema.ReqRegister
        required: true
        schema:
          $ref: '#/definitions/schema.ReqRegister'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.ResRegister'
      summary: Register
      tags:
      - Auth
swagger: "2.0"
